# For local development change /etc/hosts adding a specific subdomain that you want to test on
# i.e.
# 127.0.0.1 localhost beetlehouse.cohousing.nu
tenantdomain: "%s.cohousing.nu"

# For local development change /etc/hosts adding localdev.cohousing.nu to 127.0.0.1 to make it work
# i.e.
# 127.0.0.1 localhost localdev.cohousing.nu
admindomain: localdev.cohousing.nu

configdb:
  user: root
  password:
  host: 127.0.0.1
  port: 3306
  name: cohousing