# For local development change /etc/hosts adding a specific subdomain that you want to test on
# i.e.
# 127.0.0.1 localhost beetlehouse.cohousing.nu
tenantdomain: "%s.cohousing.nu"

tokensecret: "verysecretstringdochange"

db:
  user: root
  password:
  host: 127.0.0.1
  port: 3306
  name: cohousing